# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Model configuration dataclasses and HuggingFace → mobius conversion.

This package re-exports the public surface that used to live in
``mobius._configs`` (a single 2.6k-line module). The split keeps that
import path working while letting each concern grow in its own file:

* :mod:`._sub_configs` — pure-data dataclasses for sub-configs
  (RoPE, vision, audio, codec, TTS) shared across model families.
* :mod:`._quantization` — :class:`QuantizationConfig` and its HF parser.
* :mod:`._base` — :class:`BaseModelConfig`, :class:`ArchitectureConfig`,
  the per-model config subclasses, and the legacy ``_extract_*``
  helpers that build sub-configs from HuggingFace fields.

Follow-up PRs in this series convert the model-type switches inside the
``_extract_*`` helpers into a registry-based dispatch, and move per-model
config subclasses into their own files under ``per_model/``.
"""

from __future__ import annotations

from mobius._configs._base import (
    DEFAULT_INT,
    ArchitectureConfig,
    BambaConfig,
    BaseModelConfig,
    CausalLMConfig,
    CodeShellConfig,
    DepthAnythingConfig,
    DFlashConfig,
    Eagle3Config,
    EncoderConfig,
    FalconH1Config,
    Gemma2Config,
    Gemma3nConfig,
    Gemma3nMultiModalConfig,
    Gemma4AssistantConfig,
    Gemma4Config,
    GlmAsrConfig,
    GraniteMoeHybridConfig,
    GrokGGUFConfig,
    GroveMoEGGUFConfig,
    HyV3Config,
    HyV3MtpConfig,
    Jais2Config,
    JambaConfig,
    JetMoeConfig,
    KimiK3Config,
    KimiLinearConfig,
    Lfm2Config,
    Lfm2MoeConfig,
    Lfm2VlConfig,
    LongcatFlashConfig,
    Mamba2Config,
    MambaConfig,
    MiniMaxConfig,
    MllamaConfig,
    MMSConfig,
    MoonshineConfig,
    MoonshineStreamingConfig,
    MuseGlimmerConfig,
    NanoChatConfig,
    NemotronHConfig,
    NemotronParseConfig,
    ParakeetCTCConfig,
    Plamo2Config,
    Qwen4ExpConfig,
    Qwen35MtpConfig,
    Sam2Config,
    SegformerConfig,
    SenseNovaU1Config,
    SpeechToTextConfig,
    VisionLanguageConfig,
    WhisperConfig,
    XverseConfig,
    YolosConfig,
    Zamba2Config,
    _as_attribute_config,
    _as_int,
    _extract_audio_config,
    _extract_mrope_fields,
    _extract_rope_config,
    _extract_vision_config,
    _first,
    _first_not_none,
    _nested_rope_theta,
    _nested_rope_type,
    _normalize_rope_scaling,
    _resolve_dtype,
    _resolve_hidden_act,
    _shallow_fields,
    _shared_expert_size,
)
from mobius._configs._quantization import (
    QuantizationConfig,
    QuantizationOverride,
    QuantizedWeightFormat,
)
from mobius._configs._sub_configs import (
    AudioConfig,
    CodecDecoderConfig,
    CodecEncoderConfig,
    CodePredictorConfig,
    Gemma3nAudioConfig,
    Gemma4AudioConfig,
    RoPEConfig,
    SpeakerEncoderConfig,
    TTSConfig,
    VisionConfig,
)
from mobius._configs._world_model import WorldModelConfig
from mobius._configs.vibevoice import (
    VibeVoiceConfig,
    VibeVoiceDiffusionConfig,
    VibeVoiceStreamingConfig,
    VibeVoiceStreamingDiffusionConfig,
    VibeVoiceStreamingTokenizerConfig,
    VibeVoiceTokenizerConfig,
)
from mobius._configs.vibevoice_asr import VibeVoiceASRConfig

__all__ = [
    "DEFAULT_INT",
    "ArchitectureConfig",
    "AudioConfig",
    "BambaConfig",
    "BaseModelConfig",
    "CausalLMConfig",
    "CodeShellConfig",
    "CodePredictorConfig",
    "CodecDecoderConfig",
    "CodecEncoderConfig",
    "DepthAnythingConfig",
    "Eagle3Config",
    "EncoderConfig",
    "FalconH1Config",
    "Gemma2Config",
    "Gemma3nAudioConfig",
    "Gemma3nConfig",
    "Gemma3nMultiModalConfig",
    "Gemma4AudioConfig",
    "Gemma4Config",
    "GlmAsrConfig",
    "GrokGGUFConfig",
    "GroveMoEGGUFConfig",
    "GraniteMoeHybridConfig",
    "HyV3Config",
    "HyV3MtpConfig",
    "Jais2Config",
    "JambaConfig",
    "JetMoeConfig",
    "KimiK3Config",
    "KimiLinearConfig",
    "Lfm2Config",
    "Lfm2MoeConfig",
    "Lfm2VlConfig",
    "LongcatFlashConfig",
    "Mamba2Config",
    "MambaConfig",
    "MllamaConfig",
    "MiniMaxConfig",
    "MMSConfig",
    "MoonshineConfig",
    "MoonshineStreamingConfig",
    "MuseGlimmerConfig",
    "NanoChatConfig",
    "NemotronParseConfig",
    "NemotronHConfig",
    "ParakeetCTCConfig",
    "Plamo2Config",
    "QuantizationConfig",
    "QuantizedWeightFormat",
    "Qwen4ExpConfig",
    "QuantizationOverride",
    "Qwen35MtpConfig",
    "RoPEConfig",
    "Sam2Config",
    "SenseNovaU1Config",
    "SegformerConfig",
    "SpeechToTextConfig",
    "SpeakerEncoderConfig",
    "TTSConfig",
    "VisionConfig",
    "VisionLanguageConfig",
    "VibeVoiceConfig",
    "VibeVoiceASRConfig",
    "VibeVoiceDiffusionConfig",
    "VibeVoiceStreamingConfig",
    "VibeVoiceStreamingDiffusionConfig",
    "VibeVoiceStreamingTokenizerConfig",
    "VibeVoiceTokenizerConfig",
    "WhisperConfig",
    "XverseConfig",
    "WorldModelConfig",
    "YolosConfig",
    "Zamba2Config",
    "_as_int",
    "_extract_audio_config",
    "_extract_mrope_fields",
    "_extract_rope_config",
    "_extract_vision_config",
    "_first",
    "_first_not_none",
    "_nested_rope_theta",
    "_nested_rope_type",
    "_normalize_rope_scaling",
    "_resolve_dtype",
    "_resolve_hidden_act",
    "_as_attribute_config",
    "_shallow_fields",
    "_shared_expert_size",
    "DFlashConfig",
    "Gemma4AssistantConfig",
]
